# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_sentiment_dataset": "00_core.ipynb",
         "subsample_dataset": "00_core.ipynb",
         "preprocess_text": "00_core.ipynb",
         "parallelize": "00_core.ipynb",
         "preprocess_df_text": "00_core.ipynb",
         "calculate_word_attributes": "00_core.ipynb",
         "say_hello": "01_logistic_regression.ipynb"}

modules = ["core.py",
           "logistic_regression.py"]

doc_url = "https://hkaraoguz.github.io/deeplearningai_nlp_course1/"

git_url = "https://github.com/hkaraoguz/deeplearningai_nlp_course1/tree/master/"

def custom_doc_links(name): return None
